import { Container, Footer, Header } from "@/features/ui";
import { primaryFont, secondaryFont } from "@/styles/fonts";
import "@/styles/globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Next Minimal Starter",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${primaryFont.variable} ${secondaryFont.variable}`}>
        <div className="global-layout">
          <Header />
          <Container as="main">{children}</Container>
          <Footer />
        </div>
      </body>
    </html>
  );
}
