import { Container, Footer, Header } from "@/features/ui";
import "@/styles/globals.css";
import type { Metadata } from "next";
import { Poppins, Roboto } from "next/font/google";
import Providers from "./providers";

const primaryFont = Roboto({
  variable: "--font-primary",
  subsets: ["latin"],
  weight: ["400", "700"],
});

const secondaryFont = Poppins({
  variable: "--font-secondary",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Next Minimal Starter",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Providers>
      <html
        lang="en"
        className={`${primaryFont.variable} ${secondaryFont.variable}`}
      >
        <body>
          <div className="global-layout">
            <Header />
            <Container as="main">{children}</Container>
            <Footer />
          </div>
        </body>
      </html>
    </Providers>
  );
}
